### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mengshengwu** [CausingBrick/knapsack#1]
- [ ] A blog page to explain the algorithms
- [ ] Better code and doc
- [ ] More language implements, such as python, rust and cpp
